OCaml: update list of types
Drop the `real` type, because I can't find any evidence that
"real" was ever a type, and it certainly isn't now:
```
type t = real;;
Error: Unbound type constructor real
```

Add `result` (since OCaml 4.03).
Add `format` type (AFAICT it has been there since before `format4`)

Unfortunately we can't differentiate between 'float' the function,
and 'float' the type.

Signed-off-by: Edwin Török <edwin@etorok.net>